### ISSUE TITLE
pip3 install evtx lead to : ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by johnjohnsp1** [JPCERTCC/LogonTracer#111]
Getting this error about evtx:

Failed to build evtx
Installing collected packages: evtx
Running setup.py install for evtx ... error
ERROR: Command errored out with exit status 1:
command: /home/template/LogonTracer/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/setup.py'"'"'; file='"'"'/tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-naa187u2/install-record.txt --single-version-externally-managed --compile --install-headers /home/template/LogonTracer/include/site/python3.9/evtx
cwd: /tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/
Complete output (44 lines):
running install
running build
running build_ext
running build_rust
error: manifest path Cargo.toml does not exist
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/setup.py", line 21, in
setup(
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools/init.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
return orig.install.run(self)
File "/usr/lib/python3.9/distutils/command/install.py", line 590, in run
self.run_command('build')
File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools_rust/setuptools_ext.py", line 103, in run
build_rust.run()
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools_rust/command.py", line 52, in run
self.run_for_extension(ext)
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools_rust/build.py", line 92, in run_for_extension
dylib_paths = self.build_extension(ext)
File "/home/template/LogonTracer/lib/python3.9/site-packages/setuptools_rust/build.py", line 131, in build_extension
metadata = json.loads(check_output(metadata_command))
File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
----------------------------------------
ERROR: Command errored out with exit status 1: /home/template/LogonTracer/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/setup.py'"'"'; file='"'"'/tmp/pip-install-k6d_zuyt/evtx_022aa9be838d483e91b20221f327d5e8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-naa187u2/install-record.txt --single-version-externally-managed --compile --install-headers /home/template/LogonTracer/include/site/python3.9/evtx Check the logs for full command output.

Using VM with
Distributor ID: Ubuntu
Description: Ubuntu 21.04
Release: 21.04
Codename: hirsute
❯ python3 -V
Python 3.9.5
❯ python -V
Python 3.9.5
❯ pip -V
pip 21.1.2 from /home/template/LogonTracer/lib/python3.9/site-packages/pip (python 3.9)
❯ pip3 -V
pip 21.1.2 from /home/template/LogonTracer/lib/python3.9/site-packages/pip (python 3.9)
❯ rustc -V
rustc 1.52.1 (9bc8c42bb 2021-05-09)

pip3 install evtx just fail but pip3 install python-evtx is working fine.

pip3 install python-evtx
Requirement already satisfied: python-evtx in ./lib/python3.9/site-packages (0.7.4)
Requirement already satisfied: pyparsing==2.4.7 in ./lib/python3.9/site-packages (from python-evtx) (2.4.7)
Requirement already satisfied: hexdump==3.3 in ./lib/python3.9/site-packages (from python-evtx) (3.3)
Requirement already satisfied: configparser==4.0.2 in ./lib/python3.9/site-packages (from python-evtx) (4.0.2)
Requirement already satisfied: more-itertools==5.0.0 in ./lib/python3.9/site-packages (from python-evtx) (5.0.0)
Requirement already satisfied: zipp==1.0.0 in ./lib/python3.9/site-packages (from python-evtx) (1.0.0)
Requirement already satisfied: six in ./lib/python3.9/site-packages (from python-evtx) (1.16.0)

even if installed evtx:
evtx_dump -h
EVTX Parser 0.7.2
Omer B. omerbenamram@gmail.com
Utility to parse EVTX files

USAGE:
evtx_dump [FLAGS] [OPTIONS]

FLAGS:
--no-confirm-overwrite When set, will not ask for confirmation before overwriting files, useful for

pip install just fail

anything i miss or do wrong ?
thanks

**Comment by shu-tom** [comment]
Please use Python 3.8.
