### ISSUE TITLE
ERROR: logontracer.log status = 500

### ISSUE THREAD

**Issue by redkris** [JPCERTCC/LogonTracer#21]
Everytime I uploaded evtx files, small one or bigger one, came out with message ERROR: logontracer.log status = 500, sometimes if bigger one message keep waiting, never ending status

**Comment by Solinus11** [comment]
I have the same issue. I am not using the docker. I have the VM set up in VirtualBox. Here is what is in the shell after the failed attempt:

`/bin/sh: 1: cannot create static/logontracer.log: Directory nonexistent
127.0.0.1 - - [23/Jul/2018 09:48:57] "POST /upload HTTP/1.1" 200 -
[2018-07-23 09:48:57,156] ERROR in app: Exception on /log [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "LogonTracer/logontracer.py", line 254, in logs
    with open("/static/logontracer.log", "r") as lf:
FileNotFoundError: [Errno 2] No such file or directory: '/static/logontracer.log'
127.0.0.1 - - [23/Jul/2018 09:48:57] "GET /log HTTP/1.1" 500 -
[2018-07-23 09:48:59,129] ERROR in app: Exception on /log [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "LogonTracer/logontracer.py", line 254, in logs
    with open("/static/logontracer.log", "r") as lf:
FileNotFoundError: [Errno 2] No such file or directory: '/static/logontracer.log'
127.0.0.1 - - [23/Jul/2018 09:48:59] "GET /log HTTP/1.1" 500 -
[2018-07-23 09:48:59,173] ERROR in app: Exception on /log [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "LogonTracer/logontracer.py", line 254, in logs
    with open("/static/logontracer.log", "r") as lf:
FileNotFoundError: [Errno 2] No such file or directory: '/static/logontracer.log'
127.0.0.1 - - [23/Jul/2018 09:48:59] "GET /log HTTP/1.1" 500 -
`

**Comment by redkris** [comment]
I suggest you could use docker instead of VM because that is the easiest way to do, no error to0 much when installing, and using....better convert windows log to XML first (more fast for parsing) rather than evt files

**Comment by redkris** [comment]
I suggest you could use docker instead of VM because that is the easiest way to do, no error to0 much when installing, and using....better convert windows log to XML first (more fast for parsing) rather than evt files

**Comment by shu-tom** [comment]
If there is no authority (write privilege) in the LogonTracer folder, came out with message ERROR: logontracer.log status = 500.
Please set chmod or chown.

**Comment by Solinus11** [comment]
user has full permissions on the directories so I do not think that is the issue

*Update. I was finally able to get it working. I had to modify the script to use absolute paths for all file references contained within. All appears to be working properly now.

**Comment by shu-tom** [comment]
@Solinus11 Thanks for the your update info.
I fixed this issue.
