### ISSUE TITLE
XML import error

### ISSUE THREAD

**Issue by t-tani** [JPCERTCC/LogonTracer#26]
An error happens when importing XML file with -x option.
The error is caused by line 501 in logontracer.py. 
It works when you replace  `\'` to `\"`.

line 501)
`xml_list = fixdata.split("<Event xmlns=\'http://schemas.microsoft.com/win/2004/08/events/event\'>")`

fixed)
`xml_list = fixdata.split("<Event xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\">")`

**Comment by t-tani** [comment]
Log
```
$ python logontracer.py -x dump.xml -z +9
[*] Script start. 2018/08/01 22:02:08
[*] Time zone is 9.
[*] Last record number is 386071.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file dump.xml.
Traceback (most recent call last):
  File "logontracer.py", line 944, in <module>
    main()
  File "logontracer.py", line 939, in main
    parse_evtx(args.xmls)
  File "logontracer.py", line 774, in parse_evtx
    tohours = int((endtime - starttime).total_seconds() / 3600)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by t-tani** [comment]
thank you!
