### ISSUE TITLE
AttributeError: 'Transaction' object has no attribute 'append' 

### ISSUE THREAD

**Issue by shekharpaty** [JPCERTCC/LogonTracer#43]
Hi Team,

We are trying to load a evtx file of size 801 MB on Centos 7 server 64 bit .

python3 logontracer.py -e  test11.evtx -z +8 -u neo4j -p XXXXXXX -s localhost 

error:
[root@localhost LogonTracer-master]# python3 logontracer.py -e test11.evtx -z +8 -u neo4j -p <removed> -s localhost
[*] Script start. 2018/12/05 16:57:45
[*] Time zone is 8.
[*] Last record number is 239409.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file test11.evtx.
Traceback (most recent call last):
  File "logontracer.py", line 1028, in <module>
    main()
  File "logontracer.py", line 1016, in main
    parse_evtx(args.evtx)
  File "logontracer.py", line 636, in parse_evtx
    for node, err in xml_records(evtx_file):
  File "logontracer.py", line 526, in xml_records
    for xml, record in evtx_file_xml_view(evtx.get_file_header()):
  File "/usr/lib/python3.4/site-packages/Evtx/Views.py", line 240, in evtx_file_xml_view
    record_str = evtx_record_xml_view(record)
  File "/usr/lib/python3.4/site-packages/Evtx/Views.py", line 204, in evtx_record_xml_view
    return render_root_node(record.root())
  File "/usr/lib/python3.4/site-packages/Evtx/Views.py", line 182, in render_root_node
    for sub in root_node.substitutions():
  File "/usr/lib/python3.4/site-packages/Evtx/BinaryParser.py", line 64, in __call__
    cache[key] = self.func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 1001, in substitutions
    ofs = self.tag_and_children_length()
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 962, in tag_and_children_length
    for child in self.children():
  File "/usr/lib/python3.4/site-packages/Evtx/BinaryParser.py", line 64, in __call__
    cache[key] = self.func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 952, in children
    return self._children(end_tokens=[SYSTEM_TOKENS.EndOfStreamToken])
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 159, in _children
    ofs += child.length()
  File "/usr/lib/python3.4/site-packages/Evtx/BinaryParser.py", line 64, in __call__
    cache[key] = self.func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 177, in length
    for child in self.children():
  File "/usr/lib/python3.4/site-packages/Evtx/BinaryParser.py", line 64, in __call__
    cache[key] = self.func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 334, in children
    SYSTEM_TOKENS.CloseEmptyElementToken])
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 162, in _children
    if child.find_end_of_stream():
  File "/usr/lib/python3.4/site-packages/Evtx/BinaryParser.py", line 64, in __call__
    cache[key] = self.func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/Evtx/Nodes.py", line 186, in find_end_of_stream
    ret = child.find_end_of_stream()
AttributeError: 'NullTypeNode' object has no attribute 'find_end_of_stream'

Thankyou....

**Comment by shu-tom** [comment]
This error is from python-evtx.
https://github.com/williballenthin/python-evtx/issues/40

It's seems corrupted EVTX file or python-evtx bug.
