### ISSUE TITLE
AttributeError: 'Transaction' object has no attribute 'append'

### ISSUE THREAD

**Issue by Th4nat0s** [JPCERTCC/LogonTracer#67]
Hello 

I got the following issue when importing an evtx

```
Calculate PageRank. [*] Creating a graph data.
 Traceback (most recent call last): File "/opt/LogonTracer/logontracer.py", line 1096, in main() File "/opt/LogonTracer/logontracer.py", line 1084, in main parse_evtx(args.evtx) File "/opt/LogonTracer/logontracer.py", line 956, in parse_evtx tx.append(statement_ip, {"IP": ipaddress, "rank": ranks[ipaddress], "hostname": hostname}) AttributeError: 'Transaction' object has no attribute 'append'
```

I got this with the master and the tagged version 1.3.0, 1.3.1. 

Is the issue on my side ? 

Have a nice day.

**Comment by shu-tom** [comment]
It looks like an error with py2neo v4.
The latest version supports py2neo v4 (not support 1.3.1), so please use the latest version.

**Comment by Th4nat0s** [comment]
I run Neo4j 3.5.13.
A had just tried the docker... seems to have the same issue on my evtx

Do you confirm that I should test with the master checkout with neo 3.5.13 ?

**Comment by Th4nat0s** [comment]
Running py2neo 4.3.0 on python3

**Comment by Th4nat0s** [comment]
Seems related to "one" evtx file.... I will update on that..
