### ISSUE TITLE
Traceback (most recent call last) 'Invalid input \'1\': 

### ISSUE THREAD

**Issue by HSIS007** [JPCERTCC/LogonTracer#69]
Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/py2neo/internal/connectors.py", line 372, in run raw_result = hydrator.hydrate_result(r.data.decode("utf-8")) File "/usr/local/lib/python3.7/dist-packages/py2neo/internal/hydration/__init__.py", line 433, in hydrate_result raise HydrationError(*data["errors"]) py2neo.internal.hydration.HydrationError: {'code': 'Neo.ClientError.Statement.SyntaxError', 'message': 'Invalid input \'1\': expected whitespace, comment, \'.\', node labels, \'[\', "=~", IN, STARTS, ENDS, CONTAINS, IS, \'^\', \'*\', \'/\', \'%\', \'+\', \'-\', \'=\', \'~\', "<>", "!=", \'<\', \'>\', "<=", ">=", AND, XOR, OR, \',\', FROM GRAPH, CONSTRUCT, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, \';\' or end of input (line 2, column 52 (offset: 54))\n"MERGE (id:ID{ id:0 }) set id.changetime=2019-08-19 13:33:55, id.category=System, id.sub=SecurityStateChange"\n ^'} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/root/forensics/LogonTracer/logontracer.py", line 1101, in main() File "/root/forensics/LogonTracer/logontracer.py", line 1089, in main parse_evtx(args.evtx) File "/root/forensics/LogonTracer/logontracer.py", line 1028, in parse_evtx tx.run(statement_pl.format(**{"id": id, "changetime": policy[0], "category": category, "sub": sub})) File "/usr/local/lib/python3.7/dist-packages/py2neo/database.py", line 828, in run entities=entities)) File "/usr/local/lib/python3.7/dist-packages/py2neo/internal/connectors.py", line 377, in run raise GraphError.hydrate(e.args[0]) py2neo.database.ClientError: SyntaxError: Invalid input '1': expected whitespace, comment, '.', node labels, '[', "=~", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-', '=', '~', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, ',', FROM GRAPH, CONSTRUCT, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 2, column 52 (offset: 54)) "MERGE (id:ID{ id:0 }) set id.changetime=2019-08-19 13:33:55, id.category=System, id.sub=SecurityStateChange" ^

**Comment by shu-tom** [comment]
Thanks for your bug report. I fixed this issue.

**Comment by HSIS007** [comment]
Thank you, it is working now.
